version: 2

sources:
  - name: london_bicycles
    database: bigquery-public-data
    tables:
      - name: cycle_hire
        columns:
          - name: rental_id
            tests:
              - not_null
              - unique

          - name: duration

          - name: bike_id

          - name: end_date

          - name: end_station_id

          - name: end_station_name

          - name: start_date

          - name: start_station_id

          - name: start_station_name

          - name: end_station_logical_terminal

          - name: start_station_logical_terminal

          - name: end_station_priority_id
